DROP TABLE `Users`;

CREATE TABLE `Users` (
  `id` mediumint(8) unsigned NOT NULL auto_increment,
  `userName` TEXT default NULL,
  `userPassword` TEXT default NULL,
  `firstName` varchar(255) default NULL,
  `lastName` varchar(255) default NULL,
  `userDOB` varchar(255),
  `userCountry` varchar(100) default NULL,
  `userEmail` varchar(255) default NULL,
  PRIMARY KEY (`id`)
) AUTO_INCREMENT=1;

-- Insert into Users table
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Donecatarcu","interdum","Vance","Montgomery","19-01-31","New Zealand","ornare.egestas@velsapienimperdiet.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("cursuspurus","elit pede","Hector","Graves","19-12-13","South Korea","enim.Curabitur.massa@viverraDonectempus.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("arcuMorbi","diamProin","Salvador","Terry","18-08-18","Japan","euismod@Curabiturmassa.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tellusNunc","magnaUtt","Drake","Phillips","18-07-15","China","massa.rutrum.magna@Mauris.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("euturpis","vulputate","Gavin","Bradford","18-10-06","Australia","scelerisque.sed@netus.net");


INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Donec at arcu. Vestibulum ante ipsum primis in","interdum. Curabitur dictum. Phasellus in felis. Nulla tempor augue ac ipsum. Phasellus vitae mauris sit","Vance","Montgomery","19-01-31","Slovakia","ornare.egestas@velsapienimperdiet.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("cursus purus. Nullam scelerisque neque sed sem egestas","elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris id","Hector","Graves","19-12-13","Martinique","enim.Curabitur.massa@viverraDonectempus.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("arcu. Morbi sit amet massa. Quisque porttitor eros","diam. Proin dolor. Nulla semper tellus id nunc interdum","Salvador","Terry","18-08-18","Saint Helena, Ascension and Tristan da Cunha","euismod@Curabiturmassa.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tellus. Nunc lectus pede, ultrices a, auctor non,","magna. Ut tincidunt orci quis lectus. Nullam suscipit, est ac facilisis facilisis,","Drake","Phillips","18-07-15","Norway","massa.rutrum.magna@Mauris.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eu turpis. Nulla aliquet. Proin velit. Sed malesuada","vulputate eu, odio. Phasellus at augue id ante dictum","Gavin","Bradford","18-10-06","Armenia","scelerisque.sed@netus.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Duis risus odio, auctor vitae, aliquet nec, imperdiet","quam, elementum at, egestas a, scelerisque sed, sapien. Nunc pulvinar arcu","Kyle","Andrews","19-04-20","Tunisia","natoque.penatibus@accumsanconvallis.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("et pede. Nunc sed orci lobortis augue scelerisque","libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio, auctor","Cameron","Tucker","19-05-09","South Sudan","ligula.Aenean@Nunc.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("elementum at, egestas a, scelerisque sed, sapien. Nunc","non massa non ante bibendum ullamcorper. Duis cursus, diam at pretium","Deacon","Alford","18-09-10","Saint Vincent and The Grenadines","Donec.nibh@enimSed.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("vitae, orci. Phasellus dapibus quam quis diam. Pellentesque","metus. Aenean sed pede nec ante blandit viverra. Donec tempus,","Griffith","Rush","18-10-06","Singapore","Nulla.tempor.augue@Sedcongue.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("molestie tellus. Aenean egestas hendrerit neque. In ornare","ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et, lacinia vitae, sodales at, velit.","Kenneth","Gould","18-10-31","Equatorial Guinea","eros@risus.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("pharetra, felis eget varius ultrices, mauris ipsum porta","turpis. In condimentum. Donec at arcu. Vestibulum ante ipsum primis in faucibus orci luctus et","Ahmed","Wall","18-06-27","El Salvador","Nam@acliberonec.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("lectus justo eu arcu. Morbi sit amet massa.","Phasellus libero mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus","Curran","Skinner","18-12-01","Mali","amet@lectus.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("metus urna convallis erat, eget tincidunt dui augue","et magnis dis parturient montes, nascetur ridiculus mus. Donec dignissim","Allistair","Berry","18-10-03","Greece","tempor.erat.neque@placeratvelitQuisque.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Nunc mauris elit, dictum eu, eleifend nec, malesuada","neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec ante blandit viverra. Donec tempus,","Damian","Barrett","18-08-27","Slovenia","orci@urna.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("aliquet magna a neque. Nullam ut nisi a","adipiscing fringilla, porttitor vulputate, posuere vulputate, lacus. Cras interdum. Nunc sollicitudin commodo ipsum. Suspendisse","Tanner","Talley","19-09-20","Isle of Man","orci.Ut@Phasellusliberomauris.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tellus sem mollis dui, in sodales elit erat","a sollicitudin orci sem eget massa. Suspendisse eleifend. Cras sed leo. Cras vehicula aliquet libero. Integer","Brendan","Zimmerman","19-05-20","Dominican Republic","malesuada.id.erat@luctusutpellentesque.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tincidunt. Donec vitae erat vel pede blandit congue.","Fusce aliquet magna a neque. Nullam ut nisi a odio semper cursus. Integer mollis. Integer","Leroy","Key","19-05-19","Pitcairn Islands","lorem.auctor.quis@mus.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dui. Fusce diam nunc, ullamcorper eu, euismod ac,","lorem, auctor quis, tristique ac, eleifend vitae, erat. Vivamus nisi. Mauris nulla. Integer","Raymond","Rivas","20-01-23","Hong Kong","enim.consequat@luctusfelispurus.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("purus sapien, gravida non, sollicitudin a, malesuada id,","mauris, aliquam eu, accumsan sed, facilisis vitae, orci. Phasellus dapibus quam quis","Noah","Irwin","19-09-30","Hong Kong","lobortis.quis.pede@nonluctussit.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("mi tempor lorem, eget mollis lectus pede et","eu, ligula. Aenean euismod mauris eu elit. Nulla facilisi. Sed neque. Sed","Tyrone","Martinez","19-02-20","El Salvador","non@musDonecdignissim.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("quis turpis vitae purus gravida sagittis. Duis gravida.","vitae risus. Duis a mi fringilla mi lacinia mattis. Integer","Vernon","Stevens","19-03-01","Libya","aliquet.vel.vulputate@actellus.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Duis mi enim, condimentum eget, volutpat ornare, facilisis","quam vel sapien imperdiet ornare. In faucibus. Morbi vehicula.","Avram","Dickerson","19-04-08","India","Phasellus.fermentum@Nunccommodoauctor.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dolor vitae dolor. Donec fringilla. Donec feugiat metus","Nulla eget metus eu erat semper rutrum. Fusce dolor","Shad","Espinoza","19-01-15","Portugal","dictum.sapien@Morbinonsapien.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dolor. Quisque tincidunt pede ac urna. Ut tincidunt","blandit mattis. Cras eget nisi dictum augue malesuada malesuada.","Kibo","Olsen","18-04-16","Iceland","Curabitur.consequat.lectus@sit.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("In tincidunt congue turpis. In condimentum. Donec at","nibh dolor, nonummy ac, feugiat non, lobortis quis, pede.","Hakeem","Reeves","18-09-04","Afghanistan","magna@laoreetposuere.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("consequat auctor, nunc nulla vulputate dui, nec tempus","cursus non, egestas a, dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate ullamcorper","Dante","Williams","18-10-09","Chile","luctus.felis@Mauris.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Integer aliquam adipiscing lacus. Ut nec urna et","pede. Nunc sed orci lobortis augue scelerisque mollis. Phasellus libero","Gareth","Mathis","18-12-07","Estonia","Mauris.molestie.pharetra@Duismienim.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Aliquam gravida mauris ut mi. Duis risus odio,","nonummy. Fusce fermentum fermentum arcu. Vestibulum ante ipsum primis in faucibus orci luctus et ultrices posuere","Tad","Hebert","19-09-17","Curaçao","est.mauris.rhoncus@maurisblanditmattis.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("magna tellus faucibus leo, in lobortis tellus justo","Nunc ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est","Brenden","Weeks","19-07-10","Bahrain","neque.et@ipsumprimis.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Mauris ut quam vel sapien imperdiet ornare. In","adipiscing, enim mi tempor lorem, eget mollis lectus pede et risus. Quisque libero","Luke","Walters","20-01-02","Norway","ut@idante.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eget ipsum. Suspendisse sagittis. Nullam vitae diam. Proin","aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu ac orci.","Ivor","Sharp","20-02-03","Finland","magnis.dis@blandit.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("diam at pretium aliquet, metus urna convallis erat,","ad litora torquent per conubia nostra, per inceptos hymenaeos. Mauris ut quam","Byron","Gentry","18-11-03","Anguilla","ultrices.Vivamus.rhoncus@nisi.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("quam. Pellentesque habitant morbi tristique senectus et netus","lacinia at, iaculis quis, pede. Praesent eu dui. Cum","Lester","Jennings","19-11-14","Malta","neque@Vivamus.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("arcu. Nunc mauris. Morbi non sapien molestie orci","libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus","Chandler","Sloan","19-02-18","Pakistan","dapibus@sociosquad.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eu arcu. Morbi sit amet massa. Quisque porttitor","dolor sit amet, consectetuer adipiscing elit. Curabitur sed tortor. Integer aliquam","Matthew","Ferguson","18-07-06","Mayotte","pellentesque@Proinvelarcu.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("convallis est, vitae sodales nisi magna sed dui.","a, aliquet vel, vulputate eu, odio. Phasellus at augue id ante dictum","Marshall","Perez","20-01-07","Palestine, State of","montes@ligula.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("elit, a feugiat tellus lorem eu metus. In","dolor vitae dolor. Donec fringilla. Donec feugiat metus sit amet ante. Vivamus","Lee","Ochoa","19-07-14","Croatia","cubilia@MorbivehiculaPellentesque.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("quis accumsan convallis, ante lectus convallis est, vitae","amet, risus. Donec nibh enim, gravida sit amet, dapibus id, blandit at, nisi.","Alden","Massey","19-09-19","Iraq","Aliquam.tincidunt@molestieorci.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("erat, eget tincidunt dui augue eu tellus. Phasellus","enim consequat purus. Maecenas libero est, congue a, aliquet","Kadeem","Vega","18-07-20","Cayman Islands","eu.tellus.Phasellus@Integerurna.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("accumsan neque et nunc. Quisque ornare tortor at","tristique pharetra. Quisque ac libero nec ligula consectetuer rhoncus. Nullam velit dui, semper et,","Jonah","Pace","18-08-13","Thailand","malesuada.ut.sem@vulputate.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Cras vulputate velit eu sem. Pellentesque ut ipsum","augue eu tellus. Phasellus elit pede, malesuada vel, venenatis vel, faucibus id, libero. Donec consectetuer mauris","Marsden","Walton","19-07-01","French Southern Territories","magna.Sed.eu@mi.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dapibus id, blandit at, nisi. Cum sociis natoque","mauris. Morbi non sapien molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh.","William","Morin","18-04-19","Armenia","mauris@Naminterdumenim.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("sem, vitae aliquam eros turpis non enim. Mauris","at, libero. Morbi accumsan laoreet ipsum. Curabitur consequat, lectus sit amet luctus","Elvis","Hester","20-03-31","Mozambique","Sed.malesuada@nequeSedeget.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("pretium neque. Morbi quis urna. Nunc quis arcu","ipsum non arcu. Vivamus sit amet risus. Donec egestas. Aliquam nec enim. Nunc ut erat. Sed","Nathaniel","Mckay","18-11-26","Dominican Republic","nec.leo@temporeratneque.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("luctus et ultrices posuere cubilia Curae; Phasellus ornare.","urna. Nullam lobortis quam a felis ullamcorper viverra. Maecenas iaculis","Logan","Rose","18-11-16","Panama","senectus.et@Integer.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Proin sed turpis nec mauris blandit mattis. Cras","Vestibulum accumsan neque et nunc. Quisque ornare tortor at risus.","Walker","Mason","19-10-19","Togo","congue@mollisneccursus.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("fringilla ornare placerat, orci lacus vestibulum lorem, sit","vitae sodales nisi magna sed dui. Fusce aliquam, enim nec tempus","Matthew","Haley","19-10-19","Peru","ut@netus.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("mauris blandit mattis. Cras eget nisi dictum augue","ullamcorper, velit in aliquet lobortis, nisi nibh lacinia orci, consectetuer euismod est arcu","Kevin","Finley","19-07-30","Grenada","at@venenatis.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("nisl. Nulla eu neque pellentesque massa lobortis ultrices.","ultrices a, auctor non, feugiat nec, diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis","Branden","Callahan","19-05-24","Antarctica","eget.dictum.placerat@estMauris.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Duis risus odio, auctor vitae, aliquet nec, imperdiet","leo elementum sem, vitae aliquam eros turpis non enim. Mauris quis turpis vitae","Carson","Levine","19-08-15","Central African Republic","urna.Nunc@dictumsapienAenean.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("magna. Praesent interdum ligula eu enim. Etiam imperdiet","sem semper erat, in consectetuer ipsum nunc id enim. Curabitur massa. Vestibulum accumsan neque et nunc.","Theodore","Mcmillan","18-09-21","Saudi Arabia","faucibus@dolorFuscefeugiat.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("consequat nec, mollis vitae, posuere at, velit. Cras","quam. Pellentesque habitant morbi tristique senectus et netus et malesuada fames ac turpis","Kadeem","Stone","18-08-20","Honduras","vel.sapien.imperdiet@Cumsociisnatoque.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("suscipit, est ac facilisis facilisis, magna tellus faucibus","dui. Cras pellentesque. Sed dictum. Proin eget odio. Aliquam vulputate","Xenos","Lopez","18-11-30","Niue","neque.Nullam.nisl@massaVestibulum.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper","Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum","Mufutau","Garrett","19-03-04","Saint Kitts and Nevis","eros@blanditatnisi.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("velit egestas lacinia. Sed congue, elit sed consequat","magnis dis parturient montes, nascetur ridiculus mus. Aenean eget","Slade","Pitts","18-09-19","Andorra","ipsum.Suspendisse.sagittis@sollicitudin.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("sed consequat auctor, nunc nulla vulputate dui, nec","ac, feugiat non, lobortis quis, pede. Suspendisse dui. Fusce diam nunc, ullamcorper eu, euismod","Brennan","Hood","18-04-22","India","Ut@velitin.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("magna a neque. Nullam ut nisi a odio","malesuada. Integer id magna et ipsum cursus vestibulum. Mauris magna. Duis dignissim tempor","August","Horton","19-06-27","Chad","mattis@egetipsum.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("orci, consectetuer euismod est arcu ac orci. Ut","nibh. Quisque nonummy ipsum non arcu. Vivamus sit amet risus.","Shad","Le","18-11-29","Northern Mariana Islands","dictum.sapien@sit.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("vulputate eu, odio. Phasellus at augue id ante","Cras convallis convallis dolor. Quisque tincidunt pede ac urna. Ut tincidunt vehicula risus. Nulla eget","Price","Wells","20-01-03","Malta","vulputate.mauris.sagittis@scelerisquemollis.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("sem. Nulla interdum. Curabitur dictum. Phasellus in felis.","semper pretium neque. Morbi quis urna. Nunc quis arcu vel","Brady","Stokes","18-09-22","Bhutan","Integer.tincidunt@volutpatNulla.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("iaculis nec, eleifend non, dapibus rutrum, justo. Praesent","eu elit. Nulla facilisi. Sed neque. Sed eget lacus. Mauris non dui nec","Hall","Mcpherson","19-12-12","Czech Republic","elit@ullamcorperviverra.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("ridiculus mus. Aenean eget magna. Suspendisse tristique neque","Sed malesuada augue ut lacus. Nulla tincidunt, neque vitae","Tobias","Graham","19-10-28","Bolivia","Donec.felis.orci@Inat.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Nam porttitor scelerisque neque. Nullam nisl. Maecenas malesuada","eu lacus. Quisque imperdiet, erat nonummy ultricies ornare, elit","Andrew","Mcfadden","19-01-25","Jamaica","dui.quis.accumsan@adlitora.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("libero nec ligula consectetuer rhoncus. Nullam velit dui,","scelerisque neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet. Proin velit. Sed","Clarke","Ingram","18-06-03","Bonaire, Sint Eustatius and Saba","massa.non@viverra.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tortor. Integer aliquam adipiscing lacus. Ut nec urna","diam. Duis mi enim, condimentum eget, volutpat ornare, facilisis eget, ipsum.","Mark","Mooney","18-08-22","Kyrgyzstan","Mauris@variuset.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("felis ullamcorper viverra. Maecenas iaculis aliquet diam. Sed","erat volutpat. Nulla dignissim. Maecenas ornare egestas ligula. Nullam","Warren","Abbott","20-03-13","Swaziland","accumsan.sed.facilisis@InloremDonec.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("neque. Sed eget lacus. Mauris non dui nec","eros. Nam consequat dolor vitae dolor. Donec fringilla. Donec feugiat metus","Sebastian","Mckay","20-03-25","Grenada","augue@sapiencursus.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eget nisi dictum augue malesuada malesuada. Integer id","et, lacinia vitae, sodales at, velit. Pellentesque ultricies dignissim lacus. Aliquam rutrum lorem ac","Clarke","Monroe","19-04-20","Colombia","auctor.non.feugiat@eget.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("elit, dictum eu, eleifend nec, malesuada ut, sem.","Sed neque. Sed eget lacus. Mauris non dui nec urna suscipit nonummy. Fusce fermentum","Marshall","Hancock","19-04-13","Palau","nonummy.ac@gravidasagittis.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Proin ultrices. Duis volutpat nunc sit amet metus.","odio semper cursus. Integer mollis. Integer tincidunt aliquam arcu. Aliquam ultrices","Julian","Baxter","19-02-21","Martinique","ut@lobortisrisusIn.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dictum placerat, augue. Sed molestie. Sed id risus","fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed, hendrerit a, arcu. Sed et libero.","Kato","Anderson","19-07-07","Monaco","Proin@ipsumsodalespurus.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Curabitur vel lectus. Cum sociis natoque penatibus et","ante blandit viverra. Donec tempus, lorem fringilla ornare placerat, orci","Callum","Fletcher","18-10-04","French Southern Territories","ac@quam.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Cum sociis natoque penatibus et magnis dis parturient","tempor diam dictum sapien. Aenean massa. Integer vitae nibh. Donec est mauris,","Samson","Glover","18-10-20","Saint Barthélemy","mi.enim.condimentum@molestieSedid.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("nec, leo. Morbi neque tellus, imperdiet non, vestibulum","a, arcu. Sed et libero. Proin mi. Aliquam gravida mauris ut mi. Duis risus odio,","Palmer","Dalton","19-03-18","Georgia","mollis.Phasellus@Nullamlobortisquam.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("nisi. Cum sociis natoque penatibus et magnis dis","magna sed dui. Fusce aliquam, enim nec tempus scelerisque, lorem ipsum sodales purus, in molestie tortor","Wing","Burks","18-09-08","Ghana","urna.Nullam@liberonecligula.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("Sed diam lorem, auctor quis, tristique ac, eleifend","luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis. Duis sit amet diam eu","Alan","Espinoza","19-09-21","India","ligula.Aliquam@Quisquepurus.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("semper cursus. Integer mollis. Integer tincidunt aliquam arcu.","mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna et ipsum cursus vestibulum.","Bevis","Brewer","18-10-15","Turkey","Donec@vestibulumMaurismagna.ca");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("fermentum risus, at fringilla purus mauris a nunc.","Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus. Aenean sed pede nec","Edward","Lamb","19-11-07","Sao Tome and Principe","non.arcu@temporeratneque.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eu tempor erat neque non quam. Pellentesque habitant","enim. Etiam gravida molestie arcu. Sed eu nibh vulputate mauris sagittis","Jonah","Rasmussen","19-01-26","Martinique","sociis.natoque.penatibus@ideratEtiam.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("vitae semper egestas, urna justo faucibus lectus, a","blandit mattis. Cras eget nisi dictum augue malesuada malesuada. Integer id magna","Kato","Barron","18-09-04","Nepal","quis.diam.Pellentesque@egetvolutpatornare.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("rutrum. Fusce dolor quam, elementum at, egestas a,","neque. Nullam nisl. Maecenas malesuada fringilla est. Mauris eu turpis. Nulla aliquet.","Drew","Brennan","18-07-25","Czech Republic","arcu@ornareFuscemollis.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("vehicula aliquet libero. Integer in magna. Phasellus dolor","aptent taciti sociosqu ad litora torquent per conubia nostra, per inceptos","Dean","Rasmussen","19-12-01","India","neque@eleifendnondapibus.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh.","Aenean egestas hendrerit neque. In ornare sagittis felis. Donec tempor, est ac mattis semper, dui lectus","Matthew","Fox","18-04-11","Denmark","non.magna@justoeu.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("elit elit fermentum risus, at fringilla purus mauris","amet orci. Ut sagittis lobortis mauris. Suspendisse aliquet molestie tellus.","Vance","Mcmillan","18-12-07","Belize","In@laciniaatiaculis.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("bibendum sed, est. Nunc laoreet lectus quis massa.","odio sagittis semper. Nam tempor diam dictum sapien. Aenean","Garrett","Donaldson","19-08-26","Laos","enim@lobortisrisusIn.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("mattis. Integer eu lacus. Quisque imperdiet, erat nonummy","ornare egestas ligula. Nullam feugiat placerat velit. Quisque varius. Nam porttitor scelerisque neque. Nullam nisl.","Yuli","Calderon","19-02-24","Italy","urna.suscipit.nonummy@urna.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("feugiat metus sit amet ante. Vivamus non lorem","vel lectus. Cum sociis natoque penatibus et magnis dis parturient montes, nascetur ridiculus","Raymond","Lara","19-07-17","Iran","enim.Mauris@enim.org");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("in consequat enim diam vel arcu. Curabitur ut","aliquet nec, imperdiet nec, leo. Morbi neque tellus, imperdiet non, vestibulum nec, euismod in,","Upton","Fox","18-06-25","Uganda","euismod@nec.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dolor, tempus non, lacinia at, iaculis quis, pede.","mauris, rhoncus id, mollis nec, cursus a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo","Davis","Norris","19-01-14","Laos","Nulla.eu@Cras.com");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("massa. Suspendisse eleifend. Cras sed leo. Cras vehicula","eu turpis. Nulla aliquet. Proin velit. Sed malesuada augue ut lacus. Nulla tincidunt,","Ian","Dotson","19-02-24","Bahrain","ut.nulla.Cras@sagittis.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("aliquet molestie tellus. Aenean egestas hendrerit neque. In","sociis natoque penatibus et magnis dis parturient montes, nascetur","Dorian","Harrison","19-04-06","Kiribati","in@ultricesmauris.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("mollis. Integer tincidunt aliquam arcu. Aliquam ultrices iaculis","mus. Aenean eget magna. Suspendisse tristique neque venenatis lacus.","Upton","Merrill","18-08-30","Christmas Island","Class@commodoat.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("conubia nostra, per inceptos hymenaeos. Mauris ut quam","a, enim. Suspendisse aliquet, sem ut cursus luctus, ipsum leo elementum sem, vitae","Calvin","Avila","19-11-13","Saint Helena, Ascension and Tristan da Cunha","porttitor@nonummy.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("eu eros. Nam consequat dolor vitae dolor. Donec","Ut semper pretium neque. Morbi quis urna. Nunc quis arcu vel quam","Jordan","Snyder","18-10-08","Greece","magna.nec@orciUt.co.uk");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("dignissim pharetra. Nam ac nulla. In tincidunt congue","ullamcorper eu, euismod ac, fermentum vel, mauris. Integer sem elit, pharetra ut, pharetra sed,","Hayes","Delaney","18-09-26","Sierra Leone","at.pretium@Quisquefringilla.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("tempus mauris erat eget ipsum. Suspendisse sagittis. Nullam","faucibus orci luctus et ultrices posuere cubilia Curae; Phasellus ornare. Fusce mollis.","Dorian","Odonnell","18-07-02","Cocos (Keeling) Islands","Pellentesque.habitant@liberonec.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("enim. Suspendisse aliquet, sem ut cursus luctus, ipsum","molestie orci tincidunt adipiscing. Mauris molestie pharetra nibh. Aliquam ornare, libero","Todd","Carr","18-04-13","Vanuatu","Cras.eu@montesnasceturridiculus.net");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("elit, a feugiat tellus lorem eu metus. In","quam. Pellentesque habitant morbi tristique senectus et netus et malesuada","Abel","Fitzpatrick","20-01-26","Algeria","gravida.non.sollicitudin@arcuVestibulumut.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("euismod in, dolor. Fusce feugiat. Lorem ipsum dolor","Proin non massa non ante bibendum ullamcorper. Duis cursus, diam","Eaton","Bowen","18-12-09","New Caledonia","euismod.est.arcu@magnaatortor.edu");
INSERT INTO `Users` (`userName`,`userPassword`,`firstName`,`lastName`,`userDOB`,`userCountry`,`userEmail`) VALUES ("nisi. Aenean eget metus. In nec orci. Donec","Aenean eget magna. Suspendisse tristique neque venenatis lacus. Etiam bibendum fermentum metus.","Hilel","Curtis","19-08-31","Lebanon","sed.facilisis.vitae@porttitoreros.co.uk");
